name: Build ssocr.pyz

on:
  push:
    paths:
      - 'ssocr/**'
      - '.github/workflows/*'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'ssocr/**'
      - '.github/workflows/*'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Building the application
      run: |
        mkdir build | Out-Null

        Copy-Item -Path ssocr/* -Destination build/ -Recurse -Force

        python -m compileall -f -b build/

        Get-ChildItem -Path build/ -Filter *.py -Recurse | Remove-Item -Force

        if (Test-Path build/main.pyc) {
          Move-Item -Path build/main.pyc -Destination build/__main__.pyc -Force
        }

        python -m zipapp build --output dist/ssocr.pyz --compress

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ssocr.pyz
        path: dist/ssocr.pyz
